config/routes.rb
Rails.application.routes.draw do
  root 'uploads#new'
  resources :uploads, only: [:create]
  get 'uploads/demo', to: 'uploads#demo', as: 'demo'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def create
    if params[:log].present?
      @log = params[:log]
      if valid_log_file?(@log)
        log_path = Rails.root.join('public', 'uploads', @log.original_filename)
        File.open(Rails.root.join('public', 'uploads', @log.original_filename), 'wb') do |log|
          log.write(@log.read)
        end

        log = File.read(log_path)
        @matches = UploadsHelper.parse_log(log)

        render 'show'
      else
        redirect_to root_path, error: "Only .log logs are allowed."
      end
    else
      redirect_to root_path, alert: "Please select a log to upload."
    end
  end

  def demo
    log_path = Rails.root.join('public', 'uploads', 'qgames.log')

    log = File.read(log_path)
    @matches = UploadsHelper.parse_log(log)

    render 'show'
  end

  def valid_log_file?(log)
    log.original_filename.end_with?('.log') && ['text/plain', 'application/octet-stream'].include?(log.content_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
  DEATH_CAUSE_MAPPER = {
    'MOD_UNKNOWN' => 'Doing something mysterious',
    'MOD_SHOTGUN' => 'Shotgun',
    'MOD_GAUNTLET' => 'Gauntlets',
    'MOD_MACHINEGUN' => 'Machine gun',
    'MOD_GRENADE' => 'Grenade Launcher',
    'MOD_GRENADE_SPLASH' => "Grenade Launcher's splash damage",
    'MOD_ROCKET' => 'Direct rocket to the face',
    'MOD_ROCKET_SPLASH' => "Rocket splash damage",
    'MOD_PLASMA' => 'Plasma Gun',
    'MOD_PLASMA_SPLASH' => "Plasma gun's splash damage",
    'MOD_RAILGUN' => 'Railgun',
    'MOD_LIGHTNING' => 'Lightning Gun',
    'MOD_BFG' => 'BFG10K',
    'MOD_BFG_SPLASH' => "BFG10K's splash damage",
    'MOD_WATER' => 'Drowning in water',
    'MOD_SLIME' => 'Melting in slime',
    'MOD_LAVA' => 'Swimming in lava',
    'MOD_CRUSH' => 'Liking high pressures',
    'MOD_TELEFRAG' => 'Telefragged',
    'MOD_FALLING' => 'Spontaneus vertical deacceleration',
    'MOD_SUICIDE' => 'Ended their own life',
    'MOD_TARGET_LASER' => 'Following lasers',
    'MOD_TRIGGER_HURT' => 'Not watching their step',
    'MOD_NAIL' => 'Stepping on a nail',
    'MOD_CHAINGUN' => 'Chaingun',
    'MOD_PROXIMITY_MINE' => 'Proximity Mine',
    'MOD_KAMIKAZE' => 'Doing the kamikaze',
    'MOD_JUICED' => 'Getting juiced',
    'MOD_GRAPPLE' => 'Grappling Hook'
  }.freeze

  WEAPON_NAME_MAPPER = {
    'MOD_TELEFRAG' => 'Telefragging',
    'MOD_SHOTGUN' => 'Shotgun',
    'MOD_GAUNTLET' => 'Gauntlets',
    'MOD_MACHINEGUN' => 'Machine gun',
    'MOD_GRENADE' => 'Grenade Launcher',
    'MOD_GRENADE_SPLASH' => "Grenade Launcher",
    'MOD_ROCKET' => 'Rocket Launcher',
    'MOD_ROCKET_SPLASH' => "Rocket Launcher",
    'MOD_PLASMA' => 'Plasma Gun',
    'MOD_PLASMA_SPLASH' => "Plasma Gun",
    'MOD_RAILGUN' => 'Railgun',
    'MOD_LIGHTNING' => 'Lightning Gun',
    'MOD_BFG' => 'BFG10K',
    'MOD_BFG_SPLASH' => "BFG10K",
    'MOD_CHAINGUN' => 'Chaingun',
    'MOD_PROXIMITY_MINE' => 'Proximity Mine',
    'MOD_GRAPPLE' => 'Grappling Hook'
  }.freeze

  def self.parse_log(log)
    matches = log.split('InitGame')
    matches.shift
    mount_parsed_jsons(matches)
  end

  def self.mount_parsed_jsons(matches)
    response = {}

    matches.each_with_index do |round, i|
      key = "game_#{i + 1}"

      players = round.scan(/n\\(.*?)\\t/).uniq.flatten.sort
      all_kills = round.scan(/(\w+|<\w+>)\s+killed\s+(.*)\s+by\s+(.*)/)
      kill_info = round_kill_info(all_kills)

      response[key] =
        {
          players: players,
          total_kills: kill_info[:player_kills],
          total_deaths: kill_info[:death_count],
          world_deaths: kill_info[:world_kills],
          player_info: player_statistics(all_kills, players, round)
        }

      mvp_candidate = response[key][:player_info].max_by { |_k, v| v[:final_score] }
      response[key][:mvp] = mvp_candidate[1][:final_score] > 0 ? mvp_candidate[0] : 'No MVP'
    end

    response
  end

  def self.round_kill_info(all_kills)
    {
      death_count: all_kills.size,
      world_kills: all_kills.select { |kill| kill[0] == '<world>' }.size,
      player_kills: all_kills.reject { |kill| kill[0] == '<world>' }.size
    }
  end

  def self.player_statistics(kills, players, round)
    player_info = {}

    players.each do |player|
      player_kills = kills.select { |kill| kill[0] == player }
      kills_without_self = player_kills.reject { |kill| kill[2] == player }
      player_deaths = kills.select { |kill| kill[1] == player }
      player_world_deaths = kills.select { |kill| kill[0] == '<world>' && kill[2] == player }

      player_info[player] = {
        kills: kills_without_self.size,
        deaths: player_deaths.size,
        world_deaths: player_world_deaths.size,
        final_score: player_kills.size - player_world_deaths.size,
        extra_details: extra_details(kills_without_self, player_deaths)
      }
    end

    player_info
  end

  def self.extra_details(kills, deaths)
    response = {
      kills_per_weapon: {},
      death_causes: {},
      self_deaths: deaths.select { |death| death[0] == death[1] }.size,
      favourite_weapon: 'None'
    }

    kill_methods = kills.map { |kill| kill[2] }.uniq
    death_methods = deaths.map { |death| death[2] }.uniq

    death_methods.each do |death|
      key = DEATH_CAUSE_MAPPER[death] || death
      response[:death_causes][key] = deaths.select { |d| d[2] == death }.size
    end
    response[:death_causes] = response[:death_causes].sort_by { |_, v| -v }.to_h

    kill_methods.each do |kill|
      key = WEAPON_NAME_MAPPER[kill] || kill
      response[:kills_per_weapon][key] ||= 0
      response[:kills_per_weapon][key] += kills.select { |k| k[2].downcase == kill.downcase }.size
    end
    response[:kills_per_weapon] = response[:kills_per_weapon].sort_by { |_, v| -v }.to_h

    if kills.count.positive?
      response[:favourite_weapon] = response[:kills_per_weapon].max_by { |_w, count| count }.first
    end

    response
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuakeLogReader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Quake log reader</h1>

<h2> Please upload a quake .log file</h2>

<%= form_with url: uploads_path, local: true, html: { multipart: true } do |form| %>
  <div class="field">
    <%= form.label :log %>
    <%= form.file_field :log, accept: '.log' %>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>

app/views/uploads/new.html.erb
<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
</head>

<div class="bg-image"></div>

<div class="log-reader">

  <h1>QUAKE 3 ARENA LOG PARSER</h1>

  <h2> PLEASE UPLOAD A QUAKE LOG FILE OR USE DEMO ONE </h2>

  <%= form_with url: uploads_path, local: true, data: { turbo: false }, html: { multipart: true } do |form| %>
    <div class="field">
      <%= form.label :LOG_FILE %>
      <%= form.file_field :log, accept: '.log' %>
    </div>
  <br>
    <div class="actions">
      <%= form.submit "UPLOAD" %>
    </div>
  <% end %>
  
  <%= button_to 'USE DEMO', demo_path, method: :get %>

</div>

<style>

  body, html {
    height: 100%;
    font-family: 'Reddit Mono', sans-serif;
  }

  .reddit-mono-<uniquifier> {
  font-family: "Reddit Mono", monospace;
  font-optical-sizing: auto;
  font-weight: <weight>;
  font-style: normal;
  }

  * {
  box-sizing: border-box;
  }

  .log-reader {
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
    color: white;
    font-weight: bold;
    border: 3px solid #f1f1f1;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 2;
    width: 80%;
    padding: 20px;
    text-align: center;
  }

  .bg-image {
    background: url("/assets/q3a_bg.jpeg") no-repeat center center;
    filter: blur(8px);
    -webkit-filter: blur(8px);
    height: 100%;    
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-size: cover;
  }
  
  .field {
    margin-left: 80px;
  }
</style>

app/views/uploads/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'match_parser' %>
    <%= stylesheet_link_tag 'match_viewer', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Reddit+Mono:wght@200..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <div class="bg-image"></div>
    <div class="content-wrapper">
      <div class="log-parser">
        <h1>Quake log reader</h1>
        <h3>Number of matches: <%= @matches.size %></h3>
        <br>
        <% @matches.each_with_index do |match, i| %>
          <div class="match-container">
            <div class="match-box" id="match-box-<%= i + 1 %>">
              <h3>Match <%= i + 1 %></h3>
              <p> Number of players: <%= match[1][:players].size %></p>
              <p> 
                <%= match[1][:total_kills] %> <span style='color: red;'>Kills</span>, 
                <%= match[1][:total_deaths] %> <span style='color: cyan;'>Deaths</span>, 
                <%= match[1][:world_deaths] %> <span style='color: green;'>World deaths</span>
                <br>
                MVP: <% if match[1][:mvp] == 'No MVP' %>
                    <span style='color: gray;'>None</span>
                  <% else %>
                    <span style='color: gold;'><%= match[1][:mvp] %></span>
                  <% end %>
              </p>
            </div>
            <div class="bg-text" id="match-info-<%= i + 1 %>" style="display: none;">
              <%= match[1].to_json %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="match-all-info-box">
        <h2>Match Details</h2>
        <div class="selected-match">
          <pre id="json-content"></pre>
        </div>
      </div>
    </div>
    <script>
      initializeMatchClickEvents();
    </script>
  </body>
</html>